id: CVE-2024-13700-embed_swagger_ui-20e2454f-f49b-413f-ae45-8b628b30a780

info:
  name: >
    Embed Swagger UI <= 1.0.0 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    The Embed Swagger UI plugin for WordPress is vulnerable to Stored Cross-Site Scripting via the plugin's 'wpsgui' shortcode in all versions up to, and including, 1.0.0 due to insufficient input sanitization and output escaping on user supplied attributes. This makes it possible for authenticated attackers, with contributor-level access and above, to inject arbitrary web scripts in pages that will execute whenever a user accesses an injected page.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/20e2454f-f49b-413f-ae45-8b628b30a780?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 6.4
    cve-id: CVE-2024-13700
  metadata:
    fofa-query: "wp-content/plugins/embed-swagger-ui/"
    google-query: inurl:"/wp-content/plugins/embed-swagger-ui/"
    shodan-query: 'http.html:"wp-content/plugins/embed-swagger-ui/"'
  tags: cve,wordpress,wp-plugin,embed-swagger-ui,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/embed-swagger-ui/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "embed-swagger-ui"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.0.0')