id: CVE-2024-9368-aggregator_advanced_settings-838bfa4c-2eb7-4f76-a6c3-ab4684f3913c

info:
  name: >
    Aggregator Advanced Settings <= 1.2.1 - Authenticated (Author+) Stored Cross-Site Scripting via SVG File Upload
  author: topscoder
  severity: low
  description: >
    The Aggregator Advanced Settings plugin for WordPress is vulnerable to Stored Cross-Site Scripting via SVG File uploads in all versions up to, and including, 1.2.1 due to insufficient input sanitization and output escaping. This makes it possible for authenticated attackers, with Author-level access and above, to inject arbitrary web scripts in pages that will execute whenever a user accesses the SVG file.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/838bfa4c-2eb7-4f76-a6c3-ab4684f3913c?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 6.4
    cve-id: CVE-2024-9368
  metadata:
    fofa-query: "wp-content/plugins/aggregator-advanced-settings/"
    google-query: inurl:"/wp-content/plugins/aggregator-advanced-settings/"
    shodan-query: 'http.html:"wp-content/plugins/aggregator-advanced-settings/"'
  tags: cve,wordpress,wp-plugin,aggregator-advanced-settings,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/aggregator-advanced-settings/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "aggregator-advanced-settings"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.2.1')