id: CVE-2022-45357-1003_mortgage_application-63567094-9fb1-44b2-a3e6-99194389c4b6

info:
  name: >
    1003 Mortgage Application <= 1.75 - Unauthenticated CSV Injection
  author: topscoder
  severity: medium
  description: >
    The 1003 Mortgage Application plugin for WordPress is vulnerable to CSV Injection in versions up to, and including, 1.75. This allows unauthenticated attackers to embed untrusted input into exported CSV files, which can result in code execution when these files are downloaded and opened on a local system with a vulnerable configuration.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/63567094-9fb1-44b2-a3e6-99194389c4b6?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:L
    cvss-score: 6.5
    cve-id: CVE-2022-45357
  metadata:
    fofa-query: "wp-content/plugins/1003-mortgage-application/"
    google-query: inurl:"/wp-content/plugins/1003-mortgage-application/"
    shodan-query: 'http.html:"wp-content/plugins/1003-mortgage-application/"'
  tags: cve,wordpress,wp-plugin,1003-mortgage-application,medium,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/1003-mortgage-application/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "1003-mortgage-application"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.75')