id: CVE-2022-45368-1003_mortgage_application-d5d77105-19a8-40eb-8a9c-aa519a757a8d

info:
  name: >
    1003 Mortgage Application <= 1.75 - Authenticated (Subscriber+) Arbitrary File Download
  author: topscoder
  severity: low
  description: >
    The 1003 Mortgage Application plugin for WordPress is vulnerable to arbitrary file download in versions up to, and including, 1.75 due to incorrect controls on the mortgate_application_download_file_callback() function. This makes it possible for authenticated attackers, with subscriber-level access or higher to download arbitrary files on the affected site's server, including database configuration files.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/d5d77105-19a8-40eb-8a9c-aa519a757a8d?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N
    cvss-score: 7.1
    cve-id: CVE-2022-45368
  metadata:
    fofa-query: "wp-content/plugins/1003-mortgage-application/"
    google-query: inurl:"/wp-content/plugins/1003-mortgage-application/"
    shodan-query: 'http.html:"wp-content/plugins/1003-mortgage-application/"'
  tags: cve,wordpress,wp-plugin,1003-mortgage-application,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/1003-mortgage-application/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "1003-mortgage-application"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.75')