id: swagger-846324c7e6ee105f2a750447d7a4292e

info:
  name: >
    ThemeBlvd Themes/Plugins (Various Versions) - Missing Authorization Checks
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/bb5178f4-356b-4352-96ca-500e49006f8a?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/themes/swagger/"
    google-query: inurl:"/wp-content/themes/swagger/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-theme,swagger,high

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/themes/swagger/style.css"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Version: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Version: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "swagger"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.1.4')