id: CVE-2015-1000005-candidate_application_form-d1772e79-85c7-4a8e-a5d8-8d73013e6de3

info:
  name: >
    Candidate Application Form <= 1.3 - Arbitrary File Download
  author: topscoder
  severity: high
  description: >
    The Candidate Application Form plugin for WordPress is vulnerable to Arbitrary File Download in versions up to, and including, 1.3. This is due to insufficient sanitization in the 'downloadpdffile.php' file. This makes it possible for unauthenticated attackers to download files containing sensitive information.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/d1772e79-85c7-4a8e-a5d8-8d73013e6de3?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cve-id: CVE-2015-1000005
  metadata:
    fofa-query: "wp-content/plugins/candidate-application-form/"
    google-query: inurl:"/wp-content/plugins/candidate-application-form/"
    shodan-query: 'http.html:"wp-content/plugins/candidate-application-form/"'
  tags: cve,wordpress,wp-plugin,candidate-application-form,high,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/candidate-application-form/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "candidate-application-form"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.3')