id: CVE-2025-13358-codeconfig_accessibility-fe324d4d-eb52-4eeb-ad91-072a6e84d9ba

info:
  name: >
    Accessiy By CodeConfig Accessibility <= 1.0.0 - Missing Authorization to Authenticated (Subscriber+) Arbitrary Page Creation
  author: topscoder
  severity: low
  description: >
    The Accessiy By CodeConfig Accessibility plugin for WordPress is vulnerable to unauthorized page creation due to missing authorization checks in versions up to, and including, 1.0.0. This is due to the plugin not performing capability checks in the `Settings::createPage()` function. This makes it possible for authenticated attackers, with Subscriber-level access and above, to create arbitrary published pages on the site via the `ccpcaCreatePage` AJAX action.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/fe324d4d-eb52-4eeb-ad91-072a6e84d9ba?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N
    cvss-score: 5.3
    cve-id: CVE-2025-13358
  metadata:
    fofa-query: "wp-content/plugins/codeconfig-accessibility/"
    google-query: inurl:"/wp-content/plugins/codeconfig-accessibility/"
    shodan-query: 'http.html:"wp-content/plugins/codeconfig-accessibility/"'
  tags: cve,wordpress,wp-plugin,codeconfig-accessibility,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/codeconfig-accessibility/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "codeconfig-accessibility"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.0.0')