id: CVE-2025-15440-ione360_configurator-02fe87e4-4275-4652-aec1-b25547071796

info:
  name: >
    iONE360 configurator <= 2.0.57 - Unauthenticated Stored Cross-Site Scripting via Contact Form Parameters
  author: topscoder
  severity: high
  description: >
    The iONE360  configurator plugin for WordPress is vulnerable to Stored Cross-Site Scripting via the Contact Form Parameters in all versions up to, and including, 2.0.57 due to insufficient input sanitization and output escaping. This makes it possible for unauthenticated attackers to inject arbitrary web scripts in pages that will execute whenever a user accesses an injected page.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/02fe87e4-4275-4652-aec1-b25547071796?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 7.2
    cve-id: CVE-2025-15440
  metadata:
    fofa-query: "wp-content/plugins/ione360-configurator/"
    google-query: inurl:"/wp-content/plugins/ione360-configurator/"
    shodan-query: 'http.html:"wp-content/plugins/ione360-configurator/"'
  tags: cve,wordpress,wp-plugin,ione360-configurator,high,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/ione360-configurator/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "ione360-configurator"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.0.57')