id: CVE-2025-13308-application_passwords-59fdfdf3-e9fe-44d2-82f4-7a612a51d376

info:
  name: >
    Application Passwords <= 0.1.3 - Reflected Cross-Site Scripting via reject_url
  author: topscoder
  severity: medium
  description: >
    The Application Passwords plugin for WordPress is vulnerable to Reflected Cross-Site Scripting via the 'reject_url' parameter in all versions up to, and including, 0.1.3. This is due to insufficient input sanitization and output escaping on user supplied URLs, which allows javascript: URI schemes to be embedded in the reject_url parameter. This makes it possible for unauthenticated attackers to inject arbitrary web scripts that execute when a user clicks the "No, I do not approve of this connection" button, granted they can successfully trick the victim into performing an action such as clicking on a link.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/59fdfdf3-e9fe-44d2-82f4-7a612a51d376?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 5.4
    cve-id: CVE-2025-13308
  metadata:
    fofa-query: "wp-content/plugins/application-passwords/"
    google-query: inurl:"/wp-content/plugins/application-passwords/"
    shodan-query: 'http.html:"wp-content/plugins/application-passwords/"'
  tags: cve,wordpress,wp-plugin,application-passwords,medium,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/application-passwords/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "application-passwords"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 0.1.3')