id: CVE-2025-54674-product_configurator_for_woocommerce-97d5007f-1786-4a36-a3d2-b536bec31a29

info:
  name: >
    Product Configurator for WooCommerce <= 1.4.4 - Cross-Site Request Forgery
  author: topscoder
  severity: medium
  description: >
    The Product Configurator for WooCommerce plugin for WordPress is vulnerable to Cross-Site Request Forgery in all versions up to, and including, 1.4.4. This is due to missing or incorrect nonce validation on a function. This makes it possible for unauthenticated attackers to perform an unauthorized action granted they can trick a site administrator into performing an action such as clicking on a link.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/97d5007f-1786-4a36-a3d2-b536bec31a29?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N
    cvss-score: 4.3
    cve-id: CVE-2025-54674
  metadata:
    fofa-query: "wp-content/plugins/product-configurator-for-woocommerce/"
    google-query: inurl:"/wp-content/plugins/product-configurator-for-woocommerce/"
    shodan-query: 'http.html:"wp-content/plugins/product-configurator-for-woocommerce/"'
  tags: cve,wordpress,wp-plugin,product-configurator-for-woocommerce,medium,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/product-configurator-for-woocommerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "product-configurator-for-woocommerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.4.4')