id: CVE-2025-23439-tinymce_extended_config-82f525c9-c032-4770-8424-4ab7e05784f4

info:
  name: >
    TinyMCE Extended Config <= 0.1.0 - Reflected Cross-Site Scripting
  author: topscoder
  severity: medium
  description: >
    The TinyMCE Extended Config plugin for WordPress is vulnerable to Reflected Cross-Site Scripting in all versions up to, and including, 0.1.0 due to insufficient input sanitization and output escaping. This makes it possible for unauthenticated attackers to inject arbitrary web scripts in pages that execute if they can successfully trick a user into performing an action such as clicking on a link.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/82f525c9-c032-4770-8424-4ab7e05784f4?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.1
    cve-id: CVE-2025-23439
  metadata:
    fofa-query: "wp-content/plugins/tinymce-extended-config/"
    google-query: inurl:"/wp-content/plugins/tinymce-extended-config/"
    shodan-query: 'http.html:"wp-content/plugins/tinymce-extended-config/"'
  tags: cve,wordpress,wp-plugin,tinymce-extended-config,medium,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/tinymce-extended-config/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "tinymce-extended-config"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 0.1.0')