id: CVE-2025-49865-advanced_settings-926e5e4c-ea78-46f2-8fac-d9ee71aeaab8

info:
  name: >
    Advanced Settings <= 3.0.1 - Cross-Site Request Forgery
  author: topscoder
  severity: medium
  description: >
    The Advanced Settings 3 plugin for WordPress is vulnerable to Cross-Site Request Forgery in all versions up to, and including, 3.0.1. This is due to missing or incorrect nonce validation on a function. This makes it possible for unauthenticated attackers to perform an unauthorized action granted they can trick a site administrator into performing an action such as clicking on a link.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/926e5e4c-ea78-46f2-8fac-d9ee71aeaab8?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N
    cvss-score: 4.3
    cve-id: CVE-2025-49865
  metadata:
    fofa-query: "wp-content/plugins/advanced-settings/"
    google-query: inurl:"/wp-content/plugins/advanced-settings/"
    shodan-query: 'http.html:"wp-content/plugins/advanced-settings/"'
  tags: cve,wordpress,wp-plugin,advanced-settings,medium,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/advanced-settings/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "advanced-settings"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 3.0.1')